### PR TITLE
feat(author): update veberarnaud author page

### PR DESCRIPTION
**Pull request by VEBERArnaud**

### CODE REVIEW

**Comment by ElevenWilson** [comment]
1 words might be misspelled, please check them:

**Comment by ElevenWilson** [comment]
1 words might be misspelled, please check them:

**Comment by ElevenWilson** [comment]
1 words might be misspelled, please check them:

**Comment by ElevenWilson** [comment]
1 words might be misspelled, please check them:

**Review by ElevenTom — APPROVED** [review]

**Pull request merged**
