### PR TITLE
Add english article HTTPS part 1

### PR DESCRIPTION
**Pull request by BernardJeremy**

### CODE REVIEW

**Comment by ElevenWilson** [comment]
1 words might be misspelled, please check them:

**Comment by ElevenWilson** [comment]
1 words might be misspelled, please check them:

**Comment by ElevenWilson** [comment]
1 words might be misspelled, please check them:

**Comment by ElevenWilson** [comment]
1 words might be misspelled, please check them:

**Review by ElevenTom — APPROVED** [review]

**Pull request merged**
