### PR TITLE
post: monitorer son debit internet

### PR DESCRIPTION
**Pull request by VEBERArnaud**

### CODE REVIEW

**Comment by ElevenWilson** [comment]
6 words might be misspelled, please check them: Dockerfile, Entrypoint, lang, monitorer, Monitorer, VEBERArnaud

**Comment by ElevenWilson** [comment]
6 words might be misspelled, please check them: Dockerfile, Entrypoint, lang, monitorer, Monitorer, VEBERArnaud

**Comment by ElevenWilson** [comment]
6 words might be misspelled, please check them: Dockerfile, Entrypoint, lang, monitorer, Monitorer, VEBERArnaud

**Comment by ElevenWilson** [comment]
21 words might be misspelled, please check them: allone, cli, compatibilitées, concue, cron, Dockerfile, Enchainons, Entrypoint, grafana, Grafana, hostname, influxdb, InfluxDb, interessons, lang, l'url, monitorer, Monitorer, pinnées, speedtest, VEBERArnaud

**Comment by ElevenWilson** [comment]
54 words might be misspelled, please check them: Buildons, chmod, cli, Commencons, compatibilitées, concue, connait, cron, Cron, debian, d'entrypoint, d'InfluxDB, DISTRO, Dockerfile, Enchainons, entrypoint, éxecutée, forcant, gdpr, grafana, Grafana, hostname, http, influxdb, InfluxDb, InfluxDB, INFLUXDB, interessent, interessons, jq, json, lang, l'execution, l'id, lsb, l'url, Maintenat, metriques, millisecondes, monitorer, Monitorer, Ookla, pinnées, proto, PROTO, resultats, sc, speedtest, sudo, surchargeable, usr, utlisation, utlisons, VEBERArnaud

**Comment by ElevenWilson** [comment]
54 words might be misspelled, please check them: Buildons, chmod, cli, Commencons, compatibilitées, concue, connait, cron, Cron, debian, d'entrypoint, d'InfluxDB, DISTRO, Dockerfile, enchainons, entrypoint, éxecutée, forcant, gdpr, grafana, Grafana, hostname, http, influxdb, InfluxDb, InfluxDB, INFLUXDB, interessent, interessons, jq, json, lang, l'execution, l'id, lsb, l'url, Maintenat, metriques, millisecondes, monitorer, Monitorer, Ookla, pinnées, proto, PROTO, resultats, sc, speedtest, sudo, surchargeable, usr, utlisation, utlisons, VEBERArnaud

**Comment by ElevenWilson** [comment]
54 words might be misspelled, please check them: Buildons, chmod, cli, Commencons, compatibilitées, concue, connait, cron, Cron, debian, d'entrypoint, d'InfluxDB, DISTRO, Dockerfile, enchainons, entrypoint, éxecutée, forcant, gdpr, grafana, Grafana, hostname, http, influxdb, InfluxDb, InfluxDB, INFLUXDB, interessent, interessons, jq, json, lang, l'execution, l'id, lsb, l'url, Maintenat, metriques, millisecondes, monitorer, Monitorer, Ookla, pinnées, proto, PROTO, resultats, sc, speedtest, sudo, surchargeable, usr, utlisation, utlisons, VEBERArnaud

**Comment by ElevenWilson** [comment]
54 words might be misspelled, please check them: Buildons, chmod, cli, Commencons, compatibilitées, concue, connait, cron, Cron, debian, d'entrypoint, d'InfluxDB, DISTRO, Dockerfile, enchainons, entrypoint, éxecutée, forcant, gdpr, grafana, Grafana, hostname, http, influxdb, InfluxDb, InfluxDB, INFLUXDB, interessent, interessons, jq, json, lang, l'execution, l'id, lsb, l'url, Maintenat, metriques, millisecondes, monitorer, Monitorer, Ookla, pinnées, proto, PROTO, resultats, sc, speedtest, sudo, surchargeable, usr, utlisation, utlisons, VEBERArnaud

**Comment by ElevenWilson** [comment]
54 words might be misspelled, please check them: Buildons, chmod, cli, Commencons, compatibilitées, concue, connait, cron, Cron, debian, d'entrypoint, d'InfluxDB, DISTRO, Dockerfile, enchainons, entrypoint, éxecutée, forcant, gdpr, grafana, Grafana, hostname, http, influxdb, InfluxDb, InfluxDB, INFLUXDB, interessent, interessons, jq, json, lang, l'execution, l'id, lsb, l'url, Maintenat, metriques, millisecondes, monitorer, Monitorer, Ookla, pinnées, proto, PROTO, resultats, sc, speedtest, sudo, surchargeable, usr, utlisation, utlisons, VEBERArnaud

**Comment by ElevenWilson** [comment]
54 words might be misspelled, please check them: Buildons, chmod, cli, Commencons, compatibilitées, concue, connait, cron, Cron, debian, d'entrypoint, d'InfluxDB, DISTRO, Dockerfile, enchainons, entrypoint, éxecutée, forcant, gdpr, grafana, Grafana, hostname, http, influxdb, InfluxDb, InfluxDB, INFLUXDB, interessent, interessons, jq, json, lang, l'execution, l'id, lsb, l'url, Maintenat, metriques, millisecondes, monitorer, Monitorer, Ookla, pinnées, proto, PROTO, resultats, sc, speedtest, sudo, surchargeable, usr, utlisation, utlisons, VEBERArnaud

**Comment by ElevenWilson** [comment]
56 words might be misspelled, please check them: Buildons, chmod, cli, Commencons, compatibilitées, concue, connait, cron, Cron, debian, d'entrypoint, détreminer, d'InfluxDB, DISTRO, Dockerfile, enchainons, entrypoint, éxecutée, forcant, gdpr, grafana, Grafana, historiser, hostname, http, influxdb, InfluxDb, InfluxDB, INFLUXDB, interessent, interessons, jq, json, lang, l'execution, l'id, lsb, l'url, Maintenat, metriques, millisecondes, monitorer, Monitorer, Ookla, pinnées, proto, PROTO, resultats, sc, speedtest, sudo, surchargeable, usr, utlisation, utlisons, VEBERArnaud

**Comment by ElevenWilson** [comment]
56 words might be misspelled, please check them: Buildons, chmod, cli, Commencons, compatibilitées, concue, connait, cron, Cron, debian, d'entrypoint, détreminer, d'InfluxDB, DISTRO, Dockerfile, enchainons, entrypoint, éxecutée, forcant, gdpr, grafana, Grafana, historiser, hostname, http, influxdb, InfluxDb, InfluxDB, INFLUXDB, interessent, interessons, jq, json, lang, l'execution, l'id, lsb, l'url, Maintenat, metriques, millisecondes, monitorer, Monitorer, Ookla, pinnées, proto, PROTO, resultats, sc, speedtest, sudo, surchargeable, usr, utlisation, utlisons, VEBERArnaud

**Comment by ElevenWilson** [comment]
56 words might be misspelled, please check them: Buildons, chmod, cli, Commencons, compatibilitées, concue, connait, cron, Cron, debian, d'entrypoint, détreminer, d'InfluxDB, DISTRO, Dockerfile, enchainons, entrypoint, éxecutée, forcant, gdpr, grafana, Grafana, historiser, hostname, http, influxdb, InfluxDb, InfluxDB, INFLUXDB, interessent, interessons, jq, json, lang, l'execution, l'id, lsb, l'url, Maintenat, metriques, millisecondes, monitorer, Monitorer, Ookla, pinnées, proto, PROTO, resultats, sc, speedtest, sudo, surchargeable, usr, utlisation, utlisons, VEBERArnaud

**Comment by ElevenWilson** [comment]
56 words might be misspelled, please check them: Buildons, chmod, cli, Commencons, compatibilitées, concue, connait, cron, Cron, debian, d'entrypoint, détreminer, d'InfluxDB, DISTRO, Dockerfile, enchainons, entrypoint, éxecutée, forcant, gdpr, grafana, Grafana, historiser, hostname, http, influxdb, InfluxDb, InfluxDB, INFLUXDB, interessent, interessons, jq, json, lang, l'execution, l'id, lsb, l'url, Maintenat, metriques, millisecondes, monitorer, Monitorer, Ookla, pinnées, proto, PROTO, resultats, sc, speedtest, sudo, surchargeable, usr, utlisation, utlisons, VEBERArnaud

**Comment by ElevenWilson** [comment]
59 words might be misspelled, please check them: Buildons, chmod, cli, Commencons, compatibilitées, concue, connait, cron, Cron, debian, d'entrypoint, détreminer, d'InfluxDB, DISTRO, Dockerfile, enchainons, entrypoint, éxecutée, forcant, gdpr, grafana, Grafana, historiser, hostname, http, influxdb, InfluxDb, InfluxDB, INFLUXDB, interessent, interessons, jq, json, lang, l'execution, l'id, lsb, l'url, Maintenat, metriques, millisecondes, monitorer, Monitorer, Ookla, pinnées, proto, PROTO, Recupérez, redirigé, resultats, sc, speedtest, sudo, surchargeable, username, usr, utlisation, utlisons, VEBERArnaud

**Comment by ElevenWilson** [comment]
59 words might be misspelled, please check them: Buildons, chmod, cli, Commencons, compatibilitées, concue, connait, cron, Cron, debian, d'entrypoint, détreminer, d'InfluxDB, DISTRO, Dockerfile, enchainons, entrypoint, éxecutée, forcant, gdpr, grafana, Grafana, historiser, hostname, http, influxdb, InfluxDb, InfluxDB, INFLUXDB, interessent, interessons, jq, json, lang, l'execution, l'id, lsb, l'url, Maintenat, metriques, millisecondes, monitorer, Monitorer, Ookla, pinnées, proto, PROTO, Recupérez, redirigé, resultats, sc, speedtest, sudo, surchargeable, username, usr, utlisation, utlisons, VEBERArnaud

**Comment by ElevenWilson** [comment]
59 words might be misspelled, please check them: Buildons, chmod, cli, Commencons, compatibilitées, concue, connait, cron, Cron, debian, d'entrypoint, détreminer, d'InfluxDB, DISTRO, Dockerfile, enchainons, entrypoint, éxecutée, forcant, gdpr, grafana, Grafana, historiser, hostname, http, influxdb, InfluxDb, InfluxDB, INFLUXDB, interessent, interessons, jq, json, lang, l'execution, l'id, lsb, l'url, Maintenat, metriques, millisecondes, monitorer, Monitorer, Ookla, pinnées, proto, PROTO, Recupérez, redirigé, resultats, sc, speedtest, sudo, surchargeable, username, usr, utlisation, utlisons, VEBERArnaud

**Comment by ElevenWilson** [comment]
41 words might be misspelled, please check them: chmod, cli, cron, Cron, debian, d'entrypoint, d'InfluxDB, DISTRO, Dockerfile, entrypoint, gdpr, grafana, Grafana, historiser, hostname, http, influxdb, InfluxDb, InfluxDB, INFLUXDB, jq, json, lang, l'id, lsb, l'url, millisecondes, monitorer, Monitorer, Ookla, pinnées, proto, PROTO, redirigé, sc, speedtest, sudo, surchargeable, username, usr, VEBERArnaud

**Comment by ElevenWilson** [comment]
44 words might be misspelled, please check them: chmod, cli, cron, Cron, debian, d'entrypoint, d'historiser, d'InfluxDB, DISTRO, Dockerfile, entrypoint, gdpr, grafana, Grafana, hostname, http, influxdb, InfluxDb, InfluxDB, INFLUXDB, jq, json, lang, l'id, lsb, l'url, mappe, millisecondes, monitorer, Monitorer, Ookla, pinnées, proto, PROTO, redirigé, sc, speedtest, Speedtest, sudo, surchargeable, taâche, username, usr, VEBERArnaud

**Review by ElevenTom — APPROVED** [review]

**Pull request merged**
