### PR TITLE
✨ refactoring with react and new design

### PR DESCRIPTION
**Pull request by fpasquet**

### CODE REVIEW

**Review by Vik-Thor — APPROVED** [review]

**Comment by Pouzor** [comment]
> 15 avenue de la grande armée 75116 PARIS
Would be nice to set the new address :)

**Comment by Pouzor** [comment]
On the article page, we need more width for the author block 
ex : http://dev.blog.eleven-labs.com.s3-website.eu-west-2.amazonaws.com/feat/refactoring-with-react/fr/monolithe-a-microservices
Near "ÉCRIT PAR" with Marie's bio

**Comment by Pouzor** [comment]
- On this [page ](http://dev.blog.eleven-labs.com.s3-website.eu-west-2.amazonaws.com/feat/refactoring-with-react/en/responsive-accessible-typography/) the "What is the root element?" need padding
- And the dev intégration is broken (versus original [here](https://blog.eleven-labs.com/en/en/responsive-accessible-typography/))
- This part "Changing the font size in the root is generally not great." has broken render versus original
- Code block is broken too (ex : "font-size: calc(18rem / 16);")

**Comment by Pouzor** [comment]
When we refresh on a search result page (empty), we got a real broken 404

**Comment by Pouzor** [comment]
Still on this page : http://dev.blog.eleven-labs.com.s3-website.eu-west-2.amazonaws.com/feat/refactoring-with-react/en/responsive-accessible-typography/
Link in infos box seems broken. Ex below "What is the root element?"

**Review by Pouzor — APPROVED** [review]

**Comment by RedHotMan** [comment]
External links aren't working properly
See twitter link on this page per example 
http://dev.blog.eleven-labs.com.s3-website.eu-west-2.amazonaws.com/feat/refactoring-with-react/fr/authors/ajacquemin/

**Pull request merged**
