### PR TITLE
Trad article traefik + add author's page

### PR DESCRIPTION
**Pull request by dimitri-fert**

### CODE REVIEW

**Comment by ElevenWilson** [comment]
1 words might be misspelled, please check them:

**Comment by ElevenWilson** [comment]
1 words might be misspelled, please check them:

**Comment by ElevenWilson** [comment]
1 words might be misspelled, please check them:

**Comment by ElevenWilson** [comment]
1 words might be misspelled, please check them:

**Comment by ElevenWilson** [comment]
1 words might be misspelled, please check them:

**Review by ElevenTom — APPROVED** [review]

**Pull request merged**
