### PR TITLE
Translate react i18next article

### PR DESCRIPTION
**Pull request by MarieMinasyan**

### CODE REVIEW

**Comment by ElevenWilson** [comment]
22 words might be misspelled, please check them: backend, HOC, Initialisation, internationalisation, js, JSON, languagedetector, loadPath, Localise, marishka, multi, namespace, namespaces, Namespaces, npm, Pluralisation, prefered, SSR, tranlsations, useTranslation, withTranslation, xhr

**Comment by ElevenWilson** [comment]
17 words might be misspelled, please check them: backend, HOC, js, JSON, languagedetector, loadPath, Localise, marishka, multi, namespace, namespaces, Namespaces, npm, SSR, useTranslation, withTranslation, xhr

**Comment by ElevenWilson** [comment]
15 words might be misspelled, please check them: backend, HOC, js, JSON, loadPath, Localise, marishka, multi, namespace, namespaces, Namespaces, SSR, useTranslation, withTranslation, xhr

**Comment by guillemcanal** [comment]
@MarieMinasyan Je ne vois pas l'article dans la branche déployée sur AWS, c'est normal ? Merci :)

**Comment by MarieMinasyan** [comment]
@guillemcanal http://dev.blog.eleven-labs.com.s3-website.eu-west-2.amazonaws.com/feat/translate-react-i18next/en/en/react-i18next/

**Comment by ElevenWilson** [comment]
15 words might be misspelled, please check them: backend, HOC, js, JSON, loadPath, Localise, marishka, multi, namespace, namespaces, Namespaces, SSR, useTranslation, withTranslation, xhr

**Comment by ElevenWilson** [comment]
15 words might be misspelled, please check them: backend, HOC, js, JSON, loadPath, Localise, marishka, multi, namespace, namespaces, Namespaces, SSR, useTranslation, withTranslation, xhr

**Comment by ElevenWilson** [comment]
15 words might be misspelled, please check them: backend, HOC, js, JSON, loadPath, Localise, marishka, multi, namespace, namespaces, Namespaces, SSR, useTranslation, withTranslation, xhr

**Comment by ElevenWilson** [comment]
15 words might be misspelled, please check them: backend, HOC, js, JSON, loadPath, Localise, marishka, multi, namespace, namespaces, Namespaces, SSR, useTranslation, withTranslation, xhr

**Comment by ElevenWilson** [comment]
15 words might be misspelled, please check them: backend, HOC, js, JSON, loadPath, Localise, marishka, multi, namespace, namespaces, Namespaces, SSR, useTranslation, withTranslation, xhr

**Pull request merged**
