### PR TITLE
📝 added 'À la découverte de Svelte' article

### PR DESCRIPTION
**Pull request by romaindurand**
à rebase sur master quand https://github.com/eleven-labs/blog.eleven-labs.com/pull/808 sera mergée

### CODE REVIEW

**Comment by ElevenWilson** [comment]
39 words might be misspelled, please check them: baseurl, boulverse, contributeurs, CSS, d'Alexis, decouverte, derièrre, DevFest, Durand, fuiter, html, IntelliJ, interfacer, interraction, Jacomy, JS, lang, login, middleware, persos, plateforme, png, PureComponent, qu’assez, REPL, romaindurand, shouldComponentUpdate, StateOfJS, SvelteKit, Symfony, transpilé, tutoriel, TypeScript, url, urls, useCallback, useMemo, VSCode, webperformance

**Comment by ElevenWilson** [comment]
39 words might be misspelled, please check them: baseurl, boulverse, contributeurs, CSS, d'Alexis, decouverte, derièrre, DevFest, Durand, fuiter, html, IntelliJ, interfacer, interraction, Jacomy, JS, lang, login, middleware, persos, plateforme, png, PureComponent, qu’assez, REPL, romaindurand, shouldComponentUpdate, StateOfJS, SvelteKit, Symfony, transpilé, tutoriel, TypeScript, url, urls, useCallback, useMemo, VSCode, webperformance

**Comment by ElevenWilson** [comment]
36 words might be misspelled, please check them: baseurl, contributeurs, CSS, d'Alexis, decouverte, DevFest, Durand, fuiter, html, IntelliJ, interfacer, Jacomy, JS, lang, login, middleware, persos, plateforme, png, PureComponent, qu’assez, REPL, romaindurand, shouldComponentUpdate, StateOfJS, SvelteKit, Symfony, transpilé, tutoriel, TypeScript, url, urls, useCallback, useMemo, VSCode, webperformance

**Comment by ElevenWilson** [comment]
36 words might be misspelled, please check them: baseurl, contributeurs, CSS, d'Alexis, decouverte, DevFest, Durand, fuiter, html, IntelliJ, interfacer, Jacomy, JS, lang, login, middleware, persos, plateforme, png, PureComponent, qu’assez, REPL, romaindurand, shouldComponentUpdate, StateOfJS, SvelteKit, Symfony, transpilé, tutoriel, TypeScript, url, urls, useCallback, useMemo, VSCode, webperformance

**Comment by ElevenWilson** [comment]
34 words might be misspelled, please check them: baseurl, contributeurs, CSS, d'Alexis, decouverte, DevFest, Durand, fuiter, html, IntelliJ, interfacer, Jacomy, JS, lang, login, middleware, persos, plateforme, png, PureComponent, qu’assez, REPL, romaindurand, shouldComponentUpdate, StateOfJS, SvelteKit, Symfony, transpilé, tutoriel, TypeScript, useCallback, useMemo, VSCode, webperformance

**Comment by ElevenWilson** [comment]
32 words might be misspelled, please check them: baseurl, contributeurs, CSS, d'Alexis, decouverte, DevFest, fuiter, html, IntelliJ, interfacer, Jacomy, JS, lang, middleware, persos, plateforme, png, PureComponent, qu’assez, REPL, romaindurand, shouldComponentUpdate, StateOfJS, SvelteKit, Symfony, transpilé, tutoriel, TypeScript, useCallback, useMemo, VSCode, webperformance

**Comment by ElevenWilson** [comment]
32 words might be misspelled, please check them: baseurl, contributeurs, CSS, d'Alexis, decouverte, DevFest, fuiter, html, IntelliJ, interfacer, Jacomy, JS, lang, middleware, persos, plateforme, png, PureComponent, qu’assez, REPL, romaindurand, shouldComponentUpdate, StateOfJS, SvelteKit, Symfony, transpilé, tutoriel, TypeScript, useCallback, useMemo, VSCode, webperformance

**Comment by ElevenWilson** [comment]
32 words might be misspelled, please check them: baseurl, contributeurs, CSS, d'Alexis, decouverte, DevFest, fuiter, html, IntelliJ, interfacer, Jacomy, JS, lang, middleware, persos, plateforme, png, PureComponent, qu’assez, REPL, romaindurand, shouldComponentUpdate, StateOfJS, SvelteKit, Symfony, transpilé, tutoriel, TypeScript, useCallback, useMemo, VSCode, webperformance

**Review by Pouzor — APPROVED** [review]

**Pull request merged**
