### PR TITLE
Add post recruter un po pour votre projet web

### PR DESCRIPTION
**Pull request by MarionPdcf**

### CODE REVIEW

**Comment by ElevenWilson** [comment]
14 words might be misspelled, please check them: agiliste, Asana, CSPO, Jira, Kanban, KPIs, lang, mapo, png, priorisation, prioriser, PSPO, SEO, UX

**Comment by ElevenWilson** [comment]
14 words might be misspelled, please check them: agiliste, Asana, CSPO, Jira, Kanban, KPIs, lang, mapo, png, priorisation, prioriser, PSPO, SEO, UX

**Comment by ElevenWilson** [comment]
14 words might be misspelled, please check them: agiliste, Asana, CSPO, Jira, Kanban, KPIs, lang, mapo, png, priorisation, prioriser, PSPO, SEO, UX

**Comment by ElevenWilson** [comment]
16 words might be misspelled, please check them: agiliste, Asana, baseurl, CSPO, Jira, jpg, Kanban, KPIs, lang, mapo, png, priorisation, prioriser, PSPO, SEO, UX

**Comment by ElevenWilson** [comment]
16 words might be misspelled, please check them: agiliste, Asana, baseurl, CSPO, Jira, jpg, Kanban, KPIs, lang, mapo, png, priorisation, prioriser, PSPO, SEO, UX

**Comment by ElevenWilson** [comment]
16 words might be misspelled, please check them: agiliste, Asana, baseurl, CSPO, Jira, jpg, Kanban, KPIs, lang, mapo, png, priorisation, prioriser, PSPO, SEO, UX

**Comment by ElevenWilson** [comment]
16 words might be misspelled, please check them: agiliste, Asana, baseurl, CSPO, Jira, jpg, Kanban, KPIs, lang, mapo, png, priorisation, prioriser, PSPO, SEO, UX

**Review by ElevenTom — APPROVED** [review]

**Pull request merged**
