### PR TITLE
Nouvel article qui présente k9s

### PR DESCRIPTION
**Pull request by dimitri-fert**
Nouvel article qui présente l'outil `k9s`

### CODE REVIEW

**Comment by ElevenWilson** [comment]
71 words might be misspelled, please check them: autocomplétion, autosuggest, baseurl, cdcd, configmap, Configmap, configmaps, cowsay, ctrl, Customisation, customiser, d'alias, d'Ariane, decription, dépendence, dépendences, devops, d'executer, dfert, esc, executer, éxecuter, exigente, fd, formatée, fowarding, gif, Gif, gifs, hierarchie, IHM, interessant, Interessons, interragir, IP, kops, kubernetes, Kubernetes, lang, l'autoscroll, minikube, namespace, namespaces, nrmtc, ns, plusieur, png, poddisruptionbudget, popeye, pplogs, racourcis, rappellé, rappellée, Regex, réplica, replicaset, replicatset, reservé, Screenkey, selectionnée, s'executant, statefulset, surbrillance, tappe, timestamp, timestamps, userid, usr, xray, Xray, YAML

**Comment by ElevenWilson** [comment]
71 words might be misspelled, please check them: autocomplétion, autosuggest, baseurl, cdcd, configmap, Configmap, configmaps, cowsay, ctrl, Customisation, customiser, d'alias, d'Ariane, decription, dépendence, dépendences, devops, d'executer, dfert, esc, executer, éxecuter, exigente, fd, formatée, fowarding, gif, Gif, gifs, hierarchie, IHM, interessant, Interessons, interragir, IP, kops, kubernetes, Kubernetes, lang, l'autoscroll, minikube, namespace, namespaces, nrmtc, ns, plusieur, png, poddisruptionbudget, popeye, pplogs, racourcis, rappellé, rappellée, Regex, réplica, replicaset, replicatset, reservé, Screenkey, selectionnée, s'executant, statefulset, surbrillance, tappe, timestamp, timestamps, userid, usr, xray, Xray, YAML

**Comment by ElevenWilson** [comment]
71 words might be misspelled, please check them: autocomplétion, autosuggest, baseurl, cdcd, configmap, configmaps, cowsay, ctrl, ctx, Customisation, customiser, d'alias, d'Ariane, decription, dépendence, dépendences, devops, d'executer, dfert, esc, executer, éxecuter, exigente, fd, formatée, fowarding, gif, Gif, gifs, hierarchie, IHM, interessant, Interessons, interragir, IP, kops, kubernetes, Kubernetes, lang, l'autoscroll, minikube, namespace, namespaces, nrmtc, ns, plusieur, png, poddisruptionbudget, popeye, pplogs, rappellé, rappellée, readonly, Regex, réplica, replicaset, replicatset, reservé, Screenkey, selectionnée, s'executant, statefulset, surbrillance, tappe, timestamp, timestamps, userid, usr, xray, Xray, YAML

**Comment by ElevenWilson** [comment]
71 words might be misspelled, please check them: autocomplétion, autosuggest, baseurl, cdcd, configmap, configmaps, cowsay, ctrl, ctx, Customisation, customiser, d'alias, d'Ariane, decription, dépendence, dépendences, devops, d'executer, dfert, esc, executer, éxecuter, exigente, fd, formatée, fowarding, gif, Gif, gifs, hierarchie, IHM, interessant, Interessons, interragir, IP, kops, kubernetes, Kubernetes, lang, l'autoscroll, minikube, namespace, namespaces, nrmtc, ns, plusieur, png, poddisruptionbudget, popeye, pplogs, rappellé, rappellée, readonly, Regex, réplica, replicaset, replicatset, reservé, Screenkey, selectionnée, s'executant, statefulset, surbrillance, tappe, timestamp, timestamps, userid, usr, xray, Xray, YAML

**Comment by ElevenWilson** [comment]
52 words might be misspelled, please check them: autocomplétion, autosuggest, baseurl, cdcd, configmap, configmaps, cowsay, ctrl, ctx, Customisation, d'Ariane, devops, dfert, esc, éxecuter, fd, formatée, fowarding, gif, Gif, gifs, IHM, IP, kops, kubernetes, Kubernetes, lang, l'autoscroll, minikube, namespace, namespaces, nrmtc, ns, png, poddisruptionbudget, popeye, pplogs, readonly, Regex, réplica, replicaset, Screenkey, statefulset, surbrillance, tappe, timestamp, timestamps, userid, usr, xray, Xray, YAML

**Comment by ElevenWilson** [comment]
52 words might be misspelled, please check them: autocomplétion, autosuggest, baseurl, cdcd, configmap, configmaps, cowsay, ctrl, ctx, Customisation, d'Ariane, devops, dfert, esc, éxecuter, fd, formatée, fowarding, gif, Gif, gifs, IHM, IP, kops, kubernetes, Kubernetes, lang, l'autoscroll, minikube, namespace, namespaces, nrmtc, ns, png, poddisruptionbudget, popeye, pplogs, readonly, Regex, réplica, replicaset, Screenkey, statefulset, surbrillance, tappe, timestamp, timestamps, userid, usr, xray, Xray, YAML

**Comment by ElevenWilson** [comment]
51 words might be misspelled, please check them: autocomplétion, autosuggest, baseurl, cdcd, configmap, configmaps, cowsay, ctrl, ctx, Customisation, d'Ariane, devops, dfert, esc, fd, formatée, fowarding, gif, Gif, gifs, IHM, IP, kops, kubernetes, Kubernetes, lang, l'autoscroll, minikube, namespace, namespaces, nrmtc, ns, png, poddisruptionbudget, popeye, pplogs, readonly, Regex, réplica, replicaset, Screenkey, statefulset, surbrillance, tappe, timestamp, timestamps, userid, usr, xray, Xray, YAML

**Comment by ElevenWilson** [comment]
51 words might be misspelled, please check them: autocomplétion, autosuggest, baseurl, cdcd, configmap, configmaps, cowsay, ctrl, ctx, Customisation, d'Ariane, devops, dfert, esc, fd, formatée, fowarding, gif, Gif, gifs, IHM, IP, kops, kubernetes, Kubernetes, lang, l'autoscroll, minikube, namespace, namespaces, nrmtc, ns, png, poddisruptionbudget, popeye, pplogs, readonly, Regex, réplica, replicaset, Screenkey, statefulset, surbrillance, tappe, timestamp, timestamps, userid, usr, xray, Xray, YAML

**Comment by ElevenWilson** [comment]
51 words might be misspelled, please check them: autocomplétion, autosuggest, baseurl, cdcd, configmap, configmaps, cowsay, ctrl, ctx, Customisation, d'Ariane, devops, dfert, esc, fd, formatée, fowarding, gif, Gif, gifs, IHM, IP, kops, kubernetes, Kubernetes, lang, l'autoscroll, minikube, namespace, namespaces, nrmtc, ns, png, poddisruptionbudget, popeye, pplogs, readonly, Regex, réplica, replicaset, Screenkey, statefulset, surbrillance, tappe, timestamp, timestamps, userid, usr, xray, Xray, YAML

**Review by ElevenTom — APPROVED** [review]

**Pull request merged**
