### PR TITLE
fix typos

### PR DESCRIPTION
**Pull request by ch3ric**

### CODE REVIEW

**Comment by ElevenWilson** [comment]
20 words might be misspelled, please check them: BDD, captainjojo, Cypher, ee, endraw, entityManager, FormType, graphQL, GraphQL, js, lang, lanquage, Linkurious, neo, Neo, requêtage, rvb, symfony, Symfony, ubuntu

**Comment by MaxLf** [comment]
J'ai corrigé une autre typo également :)

**Comment by ElevenWilson** [comment]
20 words might be misspelled, please check them: BDD, captainjojo, Cypher, ee, endraw, entityManager, FormType, graphQL, GraphQL, js, lang, lanquage, Linkurious, neo, Neo, requêtage, rvb, symfony, Symfony, ubuntu

**Comment by ElevenWilson** [comment]
19 words might be misspelled, please check them: BDD, captainjojo, Cypher, ee, endraw, entityManager, FormType, graphQL, GraphQL, js, lang, Linkurious, neo, Neo, requêtage, rvb, symfony, Symfony, ubuntu

**Comment by ElevenWilson** [comment]
19 words might be misspelled, please check them: BDD, captainjojo, Cypher, ee, endraw, entityManager, FormType, graphQL, GraphQL, js, lang, Linkurious, neo, Neo, requêtage, rvb, symfony, Symfony, ubuntu

**Pull request merged**
