### PR TITLE
add french version to anemic domain article

### PR DESCRIPTION
**Pull request by rpierlot**

### CODE REVIEW

**Comment by ElevenWilson** [comment]
1 words might be misspelled, please check them:

**Review by lepiaf — APPROVED** [review]

**Comment by ElevenWilson** [comment]
1 words might be misspelled, please check them:

**Comment by ElevenWilson** [comment]
1 words might be misspelled, please check them:

**Comment by ElevenWilson** [comment]
1 words might be misspelled, please check them:

**Comment by ElevenWilson** [comment]
1 words might be misspelled, please check them:

**Pull request merged**
