### PR TITLE
feat(post): optimize image with imagine

### PR DESCRIPTION
**Pull request by shalomaku**

### CODE REVIEW

**Comment by ElevenWilson** [comment]
23 words might be misspelled, please check them: config, d'Imagine, GMagick, HD, imac, Imagick, jpg, ko, lang, LARG, LD, letscreate, png, redimensionnement, redimensionner, resize, skpotogbey, Soite, symfony, SYMFONY, WIDTHxHEIGHT, yml, zoomées

**Comment by nicolas-grevin** [comment]
met ton article dans _posts

**Comment by ElevenWilson** [comment]
23 words might be misspelled, please check them: config, d'Imagine, GMagick, HD, imac, Imagick, jpg, ko, lang, LARG, LD, letscreate, png, redimensionnement, redimensionner, resize, skpotogbey, Soite, symfony, SYMFONY, WIDTHxHEIGHT, yml, zoomées

**Comment by ElevenWilson** [comment]
23 words might be misspelled, please check them: config, d'Imagine, GMagick, HD, imac, Imagick, jpg, ko, lang, LARG, LD, letscreate, png, redimensionnement, redimensionner, resize, skpotogbey, Soite, symfony, SYMFONY, WIDTHxHEIGHT, yml, zoomées

**Comment by ElevenWilson** [comment]
23 words might be misspelled, please check them: config, d'Imagine, GMagick, HD, imac, Imagick, jpg, ko, lang, LARG, LD, letscreate, png, redimensionnement, redimensionner, resize, skpotogbey, Soite, symfony, SYMFONY, WIDTHxHEIGHT, yml, zoomées

**Comment by ElevenWilson** [comment]
22 words might be misspelled, please check them: config, d'Imagine, GMagick, HD, imac, Imagick, ko, lang, LARG, LD, letscreate, png, redimensionnement, redimensionner, resize, skpotogbey, Soite, symfony, SYMFONY, WIDTHxHEIGHT, yml, zoomées

**Comment by ElevenWilson** [comment]
22 words might be misspelled, please check them: config, d'Imagine, GMagick, HD, imac, Imagick, ko, lang, LARG, LD, letscreate, png, redimensionnement, redimensionner, resize, skpotogbey, Soite, symfony, SYMFONY, WIDTHxHEIGHT, yml, zoomées

**Pull request merged**
