### PR TITLE
update-article-k9s

### PR DESCRIPTION
**Pull request by dimitri-fert**
- Met à jour la date des assets et du dossier de l'article (seul le fichier markdown contenait la bonne date dans son nom)
- Rajoute du contenu text + gif dans l'article
- Change quelques phrases + boyscout

### CODE REVIEW

**Comment by ElevenWilson** [comment]
53 words might be misspelled, please check them: autocomplétion, autosuggest, baseurl, cdcd, configmap, configmaps, cowsay, ctrl, ctx, Customisation, d'Ariane, devops, dfert, esc, fd, formatée, fowarding, gif, Gif, gifs, IHM, IP, kops, kubernetes, Kubernetes, lang, l'autoscroll, l'occurence, minikube, namespace, namespaces, nrmtc, ns, png, poddisruptionbudget, popeye, pplogs, readonly, Regex, réplica, replicaset, Screenkey, selectionner, statefulset, surbrillance, tappe, timestamp, timestamps, userid, usr, xray, Xray, YAML

**Comment by ElevenWilson** [comment]
53 words might be misspelled, please check them: autocomplétion, autosuggest, baseurl, cdcd, configmap, configmaps, cowsay, ctrl, ctx, Customisation, d'Ariane, devops, dfert, esc, fd, formatée, fowarding, gif, Gif, gifs, IHM, IP, kops, kubernetes, Kubernetes, lang, l'autoscroll, l'occurence, minikube, namespace, namespaces, nrmtc, ns, png, poddisruptionbudget, popeye, pplogs, readonly, Regex, réplica, replicaset, Screenkey, selectionner, statefulset, surbrillance, tappe, timestamp, timestamps, userid, usr, xray, Xray, YAML

**Comment by ElevenWilson** [comment]
53 words might be misspelled, please check them: autocomplétion, autosuggest, baseurl, cdcd, configmap, configmaps, cowsay, ctrl, ctx, Customisation, d'Ariane, devops, dfert, esc, fd, formatée, fowarding, gif, Gif, gifs, IHM, IP, kops, kubernetes, Kubernetes, lang, l'autoscroll, l'occurence, minikube, namespace, namespaces, nrmtc, ns, png, poddisruptionbudget, popeye, pplogs, readonly, Regex, réplica, replicaset, Screenkey, selectionner, statefulset, surbrillance, tappe, timestamp, timestamps, userid, usr, xray, Xray, YAML

**Comment by ElevenWilson** [comment]
53 words might be misspelled, please check them: autocomplétion, autosuggest, baseurl, cdcd, configmap, configmaps, cowsay, ctrl, ctx, Customisation, d'Ariane, devops, dfert, esc, fd, formatée, fowarding, gif, Gif, gifs, IHM, IP, kops, kubernetes, Kubernetes, lang, l'autoscroll, l'occurence, minikube, namespace, namespaces, nrmtc, ns, png, poddisruptionbudget, popeye, pplogs, readonly, Regex, réplica, replicaset, Screenkey, selectionner, statefulset, surbrillance, tappe, timestamp, timestamps, userid, usr, xray, Xray, YAML

**Comment by ElevenWilson** [comment]
53 words might be misspelled, please check them: autocomplétion, autosuggest, baseurl, cdcd, configmap, configmaps, cowsay, ctrl, ctx, Customisation, d'Ariane, devops, dfert, esc, fd, formatée, fowarding, gif, Gif, gifs, IHM, IP, kops, kubernetes, Kubernetes, lang, l'autoscroll, l'occurence, minikube, namespace, namespaces, nrmtc, ns, png, poddisruptionbudget, popeye, pplogs, readonly, Regex, réplica, replicaset, Screenkey, selectionner, statefulset, surbrillance, tappe, timestamp, timestamps, userid, usr, xray, Xray, YAML

**Review by ElevenTom — APPROVED** [review]

**Pull request merged**
